ci: fix automerge

diff --git a/.github/workflows/auto-merge-pr-label.yml b/.github/workflows/auto-merge-pr-label.yml
--- a/.github/workflows/auto-merge-pr-label.yml
+++ b/.github/workflows/auto-merge-pr-label.yml
@@ -120,7 +120,15 @@ jobs:
           
       - name: Push changes
         run: |
-          git push origin HEAD
+          {
+            current_branch=$(git rev-parse --abbrev-ref HEAD)
+            if [[ "$current_branch" == "main" ]]; then
+              echo "ERROR: should not be on main branch."
+              echo "Please switch to a feature branch before force push."
+              exit 1
+            fi
+          }
+          git push origin HEAD -f
 
       - name: automerge PR
         run: |
